spring:
  cloud:
    config:
      name: config-client #需要从github上读取的资源名称，注意没有yml后缀名
      profile: test   #本次访问的配置项
      label: master
      uri: http://127.0.0.1:3344  #本微服务启动后先去找3344号服务，通过SpringCloudConfig获取GitHub的服务地址


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

server:
  port: 12346